# WAYPOINTS GAZEBO
- x: 0.436
  y: 8.24
  z: 0.0
  w: 0.0
- x: -7.74
  y: 8.57
  z: 0.0
  w: 0.0
- x: -7.72
  y: 0.472
  z: 0.0
  w: 0.0
- x: 11.2
  y: 6.75
  z: 0.0
  w: 0.0
- x: 11.2
  y: -5.43
  z: 0.0
  w: 0.0
# O3DE NUEVOS WAYPOINTS
# - x: -0.654
#   y: 0.218
#   z: 0.0
#   w: 0.0
# - x: -5.96
#   y: 7.05
#   z: 0.0
#   w: 0.0
# - x: 4.34
#   y: 3.94
#   z: 0.0
#   w: 0.0
# - x: 4.89
#   y: -7.81
#   z: 0.0
#   w: 0.0
# - x: -6.85
#   y: -7.32
#   z: 0.0
#   w: 0.0
